name: Build OpenROAD (Red Hat 8)

on:
  workflow_dispatch:  # allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8

    steps:
    - name: Install dependencies
      run: |
        dnf -y groupinstall "Development Tools"
        dnf -y install \
          git cmake3 \
          pcre2-devel \
          python3 python3-pip \
          bison flex \
          libX11-devel libXrender-devel libXrandr-devel \
          libxcb-devel \
          libffi-devel tcl-devel tk-devel \
          readline-devel zlib-devel \
          wget patch \
          boost-devel bzip2-devel make gcc gcc-c++ which
        alternatives --install /usr/bin/cmake cmake /usr/bin/cmake3 1

    - name: Install SWIG 4.1.1 from source
      run: |
        SWIG_VER=4.1.1
        curl -LO https://github.com/swig/swig/archive/refs/tags/v${SWIG_VER}.tar.gz
        tar xzf v${SWIG_VER}.tar.gz
        cd swig-${SWIG_VER}
        ./autogen.sh
        ./configure --prefix=/usr/local
        make -j$(nproc)
        make install
        cd ..
        
    - name: Build Boost 1.83.0 from source
      run: |
        BOOST_VER=1.83.0
        BOOST_DIR=boost_1_83_0
        curl -LO https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VER}/source/${BOOST_DIR}.tar.gz
        tar -xzf ${BOOST_DIR}.tar.gz
        cd ${BOOST_DIR}
        ./bootstrap.sh --prefix=/usr/local/boost
        ./b2 install --with-iostreams --with-filesystem --with-system --with-program_options -j$(nproc)

    - name: Clone OpenROAD (your fork)
      run: |
        git clone --recursive https://github.com/xarge-labs/OpenROAD.git
        cd OpenROAD
        git submodule update --init --recursive

    - name: Build OpenROAD
      run: |
        cd OpenROAD
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=/openroad-bin
        make -j$(nproc)
        make install

    - name: Package binary
      run: |
        tar czf openroad-rhel8.tar.gz -C / openroad-bin

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: openroad-rhel8
        path: openroad-rhel8.tar.gz
